for (let index = 0; index < 5; index++) {
    basic.showIcon(IconNames.Sad)
    basic.pause(100)
    basic.showIcon(IconNames.Confused)
    basic.pause(100)
    basic.showIcon(IconNames.Tortoise)
    basic.pause(100)
    basic.showIcon(IconNames.House)
    basic.pause(100)
    basic.showIcon(IconNames.Confused)
    basic.pause(100)
    basic.showIcon(IconNames.Happy)
    basic.pause(100)
    basic.showIcon(IconNames.SmallHeart)
    basic.pause(100)
    basic.showIcon(IconNames.Heart)
    basic.pause(100)
    music.playMelody("C5 B A G A F G F ", 122)
}
